// import Footer from './Footer'
// import Header from './Search'
//  import Message from './Message'
//  import Navbar from './Navbar'
//  import Posts from './Posts'
// import PostForm from './PostForm'
// import Login from './Login'
// import Register from './Register'


export { default as Footer } from './Footer'
export { default as Header } from './Header'
// export { default as Message } from './Message'
export { default as Navbar } from './Navbar'
export { default as AddRoutine } from './AddRoutine'
export { default as Routines} from './Routines'
// export { default as Posts } from './Posts'
export { default as Search } from './Search'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Activities} from './Activities'

